// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AddAliasApiPerformersPerformerIdAliasesPostData, AddAliasApiPerformersPerformerIdAliasesPostErrors, AddAliasApiPerformersPerformerIdAliasesPostResponses, AddSourceApiSourcesPostData, AddSourceApiSourcesPostErrors, AddSourceApiSourcesPostResponses, DeleteAliasApiAliasesAliasIdDeleteData, DeleteAliasApiAliasesAliasIdDeleteErrors, DeleteAliasApiAliasesAliasIdDeleteResponses, DeletePerformerApiPerformersPerformerIdDeleteData, DeletePerformerApiPerformersPerformerIdDeleteErrors, DeletePerformerApiPerformersPerformerIdDeleteResponses, DeleteSourceApiSourcesSourceIdDeleteData, DeleteSourceApiSourcesSourceIdDeleteErrors, DeleteSourceApiSourcesSourceIdDeleteResponses, GetSettingsApiSettingsGetData, GetSettingsApiSettingsGetResponses, GetThumbApiPerformersPerformerIdThumbGetData, GetThumbApiPerformersPerformerIdThumbGetErrors, GetThumbApiPerformersPerformerIdThumbGetResponses, HealthApiHealthGetData, HealthApiHealthGetResponses, ListPerformersApiPerformersGetData, ListPerformersApiPerformersGetErrors, ListPerformersApiPerformersGetResponses, ListSourcesApiSourcesGetData, ListSourcesApiSourcesGetResponses, LocalSubdirsApiLocalSubdirsGetData, LocalSubdirsApiLocalSubdirsGetErrors, LocalSubdirsApiLocalSubdirsGetResponses, OpenPairApiOpenPairPostData, OpenPairApiOpenPairPostErrors, OpenPairApiOpenPairPostResponses, OpenPerformerApiPerformersPerformerIdOpenPostData, OpenPerformerApiPerformersPerformerIdOpenPostErrors, OpenPerformerApiPerformersPerformerIdOpenPostResponses, PurgeMissingApiPerformersPurgeMissingPostData, PurgeMissingApiPerformersPurgeMissingPostResponses, PutSettingsApiSettingsPutData, PutSettingsApiSettingsPutErrors, PutSettingsApiSettingsPutResponses, ScanAllApiScanAllPostData, ScanAllApiScanAllPostResponses, ScanOneApiSourcesSourceIdScanPostData, ScanOneApiSourcesSourceIdScanPostErrors, ScanOneApiSourcesSourceIdScanPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health
 */
export const healthApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthApiHealthGetData, ThrowOnError>): RequestResult<HealthApiHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthApiHealthGetResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * List Sources
 */
export const listSourcesApiSourcesGet = <ThrowOnError extends boolean = false>(options?: Options<ListSourcesApiSourcesGetData, ThrowOnError>): RequestResult<ListSourcesApiSourcesGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListSourcesApiSourcesGetResponses, unknown, ThrowOnError>({ url: '/api/sources', ...options });

/**
 * Add Source
 */
export const addSourceApiSourcesPost = <ThrowOnError extends boolean = false>(options: Options<AddSourceApiSourcesPostData, ThrowOnError>): RequestResult<AddSourceApiSourcesPostResponses, AddSourceApiSourcesPostErrors, ThrowOnError> => (options.client ?? client).post<AddSourceApiSourcesPostResponses, AddSourceApiSourcesPostErrors, ThrowOnError>({
    url: '/api/sources',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Source
 */
export const deleteSourceApiSourcesSourceIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteSourceApiSourcesSourceIdDeleteData, ThrowOnError>): RequestResult<DeleteSourceApiSourcesSourceIdDeleteResponses, DeleteSourceApiSourcesSourceIdDeleteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteSourceApiSourcesSourceIdDeleteResponses, DeleteSourceApiSourcesSourceIdDeleteErrors, ThrowOnError>({ url: '/api/sources/{source_id}', ...options });

/**
 * Scan One
 */
export const scanOneApiSourcesSourceIdScanPost = <ThrowOnError extends boolean = false>(options: Options<ScanOneApiSourcesSourceIdScanPostData, ThrowOnError>): RequestResult<ScanOneApiSourcesSourceIdScanPostResponses, ScanOneApiSourcesSourceIdScanPostErrors, ThrowOnError> => (options.client ?? client).post<ScanOneApiSourcesSourceIdScanPostResponses, ScanOneApiSourcesSourceIdScanPostErrors, ThrowOnError>({ url: '/api/sources/{source_id}/scan', ...options });

/**
 * Scan All
 */
export const scanAllApiScanAllPost = <ThrowOnError extends boolean = false>(options?: Options<ScanAllApiScanAllPostData, ThrowOnError>): RequestResult<ScanAllApiScanAllPostResponses, unknown, ThrowOnError> => (options?.client ?? client).post<ScanAllApiScanAllPostResponses, unknown, ThrowOnError>({ url: '/api/scan-all', ...options });

/**
 * List Performers
 */
export const listPerformersApiPerformersGet = <ThrowOnError extends boolean = false>(options?: Options<ListPerformersApiPerformersGetData, ThrowOnError>): RequestResult<ListPerformersApiPerformersGetResponses, ListPerformersApiPerformersGetErrors, ThrowOnError> => (options?.client ?? client).get<ListPerformersApiPerformersGetResponses, ListPerformersApiPerformersGetErrors, ThrowOnError>({ url: '/api/performers', ...options });

/**
 * Get Thumb
 */
export const getThumbApiPerformersPerformerIdThumbGet = <ThrowOnError extends boolean = false>(options: Options<GetThumbApiPerformersPerformerIdThumbGetData, ThrowOnError>): RequestResult<GetThumbApiPerformersPerformerIdThumbGetResponses, GetThumbApiPerformersPerformerIdThumbGetErrors, ThrowOnError> => (options.client ?? client).get<GetThumbApiPerformersPerformerIdThumbGetResponses, GetThumbApiPerformersPerformerIdThumbGetErrors, ThrowOnError>({ url: '/api/performers/{performer_id}/thumb', ...options });

/**
 * Add Alias
 */
export const addAliasApiPerformersPerformerIdAliasesPost = <ThrowOnError extends boolean = false>(options: Options<AddAliasApiPerformersPerformerIdAliasesPostData, ThrowOnError>): RequestResult<AddAliasApiPerformersPerformerIdAliasesPostResponses, AddAliasApiPerformersPerformerIdAliasesPostErrors, ThrowOnError> => (options.client ?? client).post<AddAliasApiPerformersPerformerIdAliasesPostResponses, AddAliasApiPerformersPerformerIdAliasesPostErrors, ThrowOnError>({
    url: '/api/performers/{performer_id}/aliases',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Alias
 */
export const deleteAliasApiAliasesAliasIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteAliasApiAliasesAliasIdDeleteData, ThrowOnError>): RequestResult<DeleteAliasApiAliasesAliasIdDeleteResponses, DeleteAliasApiAliasesAliasIdDeleteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteAliasApiAliasesAliasIdDeleteResponses, DeleteAliasApiAliasesAliasIdDeleteErrors, ThrowOnError>({ url: '/api/aliases/{alias_id}', ...options });

/**
 * Delete Performer
 *
 * Single-record delete (UI offers it on missing rows only). D5: group
 * aliases are intentionally untouched.
 */
export const deletePerformerApiPerformersPerformerIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeletePerformerApiPerformersPerformerIdDeleteData, ThrowOnError>): RequestResult<DeletePerformerApiPerformersPerformerIdDeleteResponses, DeletePerformerApiPerformersPerformerIdDeleteErrors, ThrowOnError> => (options.client ?? client).delete<DeletePerformerApiPerformersPerformerIdDeleteResponses, DeletePerformerApiPerformersPerformerIdDeleteErrors, ThrowOnError>({ url: '/api/performers/{performer_id}', ...options });

/**
 * Purge Missing
 */
export const purgeMissingApiPerformersPurgeMissingPost = <ThrowOnError extends boolean = false>(options?: Options<PurgeMissingApiPerformersPurgeMissingPostData, ThrowOnError>): RequestResult<PurgeMissingApiPerformersPurgeMissingPostResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PurgeMissingApiPerformersPurgeMissingPostResponses, unknown, ThrowOnError>({ url: '/api/performers/purge-missing', ...options });

/**
 * Get Settings
 */
export const getSettingsApiSettingsGet = <ThrowOnError extends boolean = false>(options?: Options<GetSettingsApiSettingsGetData, ThrowOnError>): RequestResult<GetSettingsApiSettingsGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetSettingsApiSettingsGetResponses, unknown, ThrowOnError>({ url: '/api/settings', ...options });

/**
 * Put Settings
 */
export const putSettingsApiSettingsPut = <ThrowOnError extends boolean = false>(options: Options<PutSettingsApiSettingsPutData, ThrowOnError>): RequestResult<PutSettingsApiSettingsPutResponses, PutSettingsApiSettingsPutErrors, ThrowOnError> => (options.client ?? client).put<PutSettingsApiSettingsPutResponses, PutSettingsApiSettingsPutErrors, ThrowOnError>({
    url: '/api/settings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Open Performer
 */
export const openPerformerApiPerformersPerformerIdOpenPost = <ThrowOnError extends boolean = false>(options: Options<OpenPerformerApiPerformersPerformerIdOpenPostData, ThrowOnError>): RequestResult<OpenPerformerApiPerformersPerformerIdOpenPostResponses, OpenPerformerApiPerformersPerformerIdOpenPostErrors, ThrowOnError> => (options.client ?? client).post<OpenPerformerApiPerformersPerformerIdOpenPostResponses, OpenPerformerApiPerformersPerformerIdOpenPostErrors, ThrowOnError>({ url: '/api/performers/{performer_id}/open', ...options });

/**
 * Local Subdirs
 */
export const localSubdirsApiLocalSubdirsGet = <ThrowOnError extends boolean = false>(options: Options<LocalSubdirsApiLocalSubdirsGetData, ThrowOnError>): RequestResult<LocalSubdirsApiLocalSubdirsGetResponses, LocalSubdirsApiLocalSubdirsGetErrors, ThrowOnError> => (options.client ?? client).get<LocalSubdirsApiLocalSubdirsGetResponses, LocalSubdirsApiLocalSubdirsGetErrors, ThrowOnError>({ url: '/api/local/subdirs', ...options });

/**
 * Open Pair
 */
export const openPairApiOpenPairPost = <ThrowOnError extends boolean = false>(options: Options<OpenPairApiOpenPairPostData, ThrowOnError>): RequestResult<OpenPairApiOpenPairPostResponses, OpenPairApiOpenPairPostErrors, ThrowOnError> => (options.client ?? client).post<OpenPairApiOpenPairPostResponses, OpenPairApiOpenPairPostErrors, ThrowOnError>({
    url: '/api/open-pair',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
