// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AliasIn
 */
export type AliasIn = {
    /**
     * Alias
     */
    alias: string;
};

/**
 * AliasOut
 */
export type AliasOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Alias
     */
    alias: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthOut
 */
export type HealthOut = {
    /**
     * Status
     */
    status: string;
    /**
     * Version
     */
    version: string;
};

/**
 * OpenPairIn
 */
export type OpenPairIn = {
    /**
     * Local Path
     */
    local_path: string;
    /**
     * Performer Id
     */
    performer_id: string;
};

/**
 * PerformerListOut
 */
export type PerformerListOut = {
    /**
     * Items
     */
    items: Array<PerformerOut>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Source Count
     */
    source_count: number;
    /**
     * Missing Total
     */
    missing_total: number;
};

/**
 * PerformerOut
 */
export type PerformerOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Source Id
     */
    source_id: number;
    /**
     * Source Label
     */
    source_label: string | null;
    /**
     * Unc Path
     */
    unc_path: string;
    /**
     * Is Missing
     */
    is_missing: boolean;
    /**
     * Has Thumb
     */
    has_thumb: boolean;
    /**
     * Aliases
     */
    aliases: Array<AliasOut>;
};

/**
 * PurgeOut
 */
export type PurgeOut = {
    /**
     * Deleted
     */
    deleted: number;
};

/**
 * ScanAllItem
 */
export type ScanAllItem = {
    /**
     * Source Id
     */
    source_id: number;
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Added
     */
    added?: number | null;
    /**
     * Refreshed
     */
    refreshed?: number | null;
    /**
     * Missing
     */
    missing?: number | null;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * ScanSummary
 */
export type ScanSummary = {
    /**
     * Added
     */
    added: number;
    /**
     * Refreshed
     */
    refreshed: number;
    /**
     * Missing
     */
    missing: number;
};

/**
 * SettingsIn
 */
export type SettingsIn = {
    /**
     * Last Local Dir
     */
    last_local_dir?: string | null;
};

/**
 * SettingsOut
 */
export type SettingsOut = {
    /**
     * Last Local Dir
     */
    last_local_dir: string | null;
    /**
     * Db Path
     */
    db_path: string;
};

/**
 * SourceCreated
 */
export type SourceCreated = {
    /**
     * Id
     */
    id: number;
    /**
     * Unc Path
     */
    unc_path: string;
    /**
     * Label
     */
    label: string;
};

/**
 * SourceIn
 */
export type SourceIn = {
    /**
     * Unc Path
     */
    unc_path: string;
    /**
     * Label
     */
    label?: string | null;
};

/**
 * SourceOut
 */
export type SourceOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Unc Path
     */
    unc_path: string;
    /**
     * Label
     */
    label: string | null;
    /**
     * Last Scan At
     */
    last_scan_at: string | null;
    /**
     * Performer Count
     */
    performer_count: number;
    /**
     * Reachable
     */
    reachable: boolean;
};

/**
 * SubdirsOut
 */
export type SubdirsOut = {
    /**
     * Path
     */
    path: string;
    /**
     * Subdirs
     */
    subdirs: Array<string>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthOut;
};

export type HealthApiHealthGetResponse = HealthApiHealthGetResponses[keyof HealthApiHealthGetResponses];

export type ListSourcesApiSourcesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sources';
};

export type ListSourcesApiSourcesGetResponses = {
    /**
     * Response List Sources Api Sources Get
     *
     * Successful Response
     */
    200: Array<SourceOut>;
};

export type ListSourcesApiSourcesGetResponse = ListSourcesApiSourcesGetResponses[keyof ListSourcesApiSourcesGetResponses];

export type AddSourceApiSourcesPostData = {
    body: SourceIn;
    path?: never;
    query?: never;
    url: '/api/sources';
};

export type AddSourceApiSourcesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddSourceApiSourcesPostError = AddSourceApiSourcesPostErrors[keyof AddSourceApiSourcesPostErrors];

export type AddSourceApiSourcesPostResponses = {
    /**
     * Successful Response
     */
    201: SourceCreated;
};

export type AddSourceApiSourcesPostResponse = AddSourceApiSourcesPostResponses[keyof AddSourceApiSourcesPostResponses];

export type DeleteSourceApiSourcesSourceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Source Id
         */
        source_id: number;
    };
    query?: never;
    url: '/api/sources/{source_id}';
};

export type DeleteSourceApiSourcesSourceIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSourceApiSourcesSourceIdDeleteError = DeleteSourceApiSourcesSourceIdDeleteErrors[keyof DeleteSourceApiSourcesSourceIdDeleteErrors];

export type DeleteSourceApiSourcesSourceIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSourceApiSourcesSourceIdDeleteResponse = DeleteSourceApiSourcesSourceIdDeleteResponses[keyof DeleteSourceApiSourcesSourceIdDeleteResponses];

export type ScanOneApiSourcesSourceIdScanPostData = {
    body?: never;
    path: {
        /**
         * Source Id
         */
        source_id: number;
    };
    query?: never;
    url: '/api/sources/{source_id}/scan';
};

export type ScanOneApiSourcesSourceIdScanPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScanOneApiSourcesSourceIdScanPostError = ScanOneApiSourcesSourceIdScanPostErrors[keyof ScanOneApiSourcesSourceIdScanPostErrors];

export type ScanOneApiSourcesSourceIdScanPostResponses = {
    /**
     * Successful Response
     */
    200: ScanSummary;
};

export type ScanOneApiSourcesSourceIdScanPostResponse = ScanOneApiSourcesSourceIdScanPostResponses[keyof ScanOneApiSourcesSourceIdScanPostResponses];

export type ScanAllApiScanAllPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/scan-all';
};

export type ScanAllApiScanAllPostResponses = {
    /**
     * Response Scan All Api Scan All Post
     *
     * Successful Response
     */
    200: Array<ScanAllItem>;
};

export type ScanAllApiScanAllPostResponse = ScanAllApiScanAllPostResponses[keyof ScanAllApiScanAllPostResponses];

export type ListPerformersApiPerformersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string;
        /**
         * Include Missing
         */
        include_missing?: boolean;
        /**
         * Source Id
         */
        source_id?: number | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/performers';
};

export type ListPerformersApiPerformersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPerformersApiPerformersGetError = ListPerformersApiPerformersGetErrors[keyof ListPerformersApiPerformersGetErrors];

export type ListPerformersApiPerformersGetResponses = {
    /**
     * Successful Response
     */
    200: PerformerListOut;
};

export type ListPerformersApiPerformersGetResponse = ListPerformersApiPerformersGetResponses[keyof ListPerformersApiPerformersGetResponses];

export type GetThumbApiPerformersPerformerIdThumbGetData = {
    body?: never;
    path: {
        /**
         * Performer Id
         */
        performer_id: string;
    };
    query?: never;
    url: '/api/performers/{performer_id}/thumb';
};

export type GetThumbApiPerformersPerformerIdThumbGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetThumbApiPerformersPerformerIdThumbGetError = GetThumbApiPerformersPerformerIdThumbGetErrors[keyof GetThumbApiPerformersPerformerIdThumbGetErrors];

export type GetThumbApiPerformersPerformerIdThumbGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddAliasApiPerformersPerformerIdAliasesPostData = {
    body: AliasIn;
    path: {
        /**
         * Performer Id
         */
        performer_id: string;
    };
    query?: never;
    url: '/api/performers/{performer_id}/aliases';
};

export type AddAliasApiPerformersPerformerIdAliasesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddAliasApiPerformersPerformerIdAliasesPostError = AddAliasApiPerformersPerformerIdAliasesPostErrors[keyof AddAliasApiPerformersPerformerIdAliasesPostErrors];

export type AddAliasApiPerformersPerformerIdAliasesPostResponses = {
    /**
     * Successful Response
     */
    201: AliasOut;
};

export type AddAliasApiPerformersPerformerIdAliasesPostResponse = AddAliasApiPerformersPerformerIdAliasesPostResponses[keyof AddAliasApiPerformersPerformerIdAliasesPostResponses];

export type DeleteAliasApiAliasesAliasIdDeleteData = {
    body?: never;
    path: {
        /**
         * Alias Id
         */
        alias_id: number;
    };
    query?: never;
    url: '/api/aliases/{alias_id}';
};

export type DeleteAliasApiAliasesAliasIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAliasApiAliasesAliasIdDeleteError = DeleteAliasApiAliasesAliasIdDeleteErrors[keyof DeleteAliasApiAliasesAliasIdDeleteErrors];

export type DeleteAliasApiAliasesAliasIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAliasApiAliasesAliasIdDeleteResponse = DeleteAliasApiAliasesAliasIdDeleteResponses[keyof DeleteAliasApiAliasesAliasIdDeleteResponses];

export type DeletePerformerApiPerformersPerformerIdDeleteData = {
    body?: never;
    path: {
        /**
         * Performer Id
         */
        performer_id: string;
    };
    query?: never;
    url: '/api/performers/{performer_id}';
};

export type DeletePerformerApiPerformersPerformerIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePerformerApiPerformersPerformerIdDeleteError = DeletePerformerApiPerformersPerformerIdDeleteErrors[keyof DeletePerformerApiPerformersPerformerIdDeleteErrors];

export type DeletePerformerApiPerformersPerformerIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePerformerApiPerformersPerformerIdDeleteResponse = DeletePerformerApiPerformersPerformerIdDeleteResponses[keyof DeletePerformerApiPerformersPerformerIdDeleteResponses];

export type PurgeMissingApiPerformersPurgeMissingPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/performers/purge-missing';
};

export type PurgeMissingApiPerformersPurgeMissingPostResponses = {
    /**
     * Successful Response
     */
    200: PurgeOut;
};

export type PurgeMissingApiPerformersPurgeMissingPostResponse = PurgeMissingApiPerformersPurgeMissingPostResponses[keyof PurgeMissingApiPerformersPurgeMissingPostResponses];

export type GetSettingsApiSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type GetSettingsApiSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: SettingsOut;
};

export type GetSettingsApiSettingsGetResponse = GetSettingsApiSettingsGetResponses[keyof GetSettingsApiSettingsGetResponses];

export type PutSettingsApiSettingsPutData = {
    body: SettingsIn;
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type PutSettingsApiSettingsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutSettingsApiSettingsPutError = PutSettingsApiSettingsPutErrors[keyof PutSettingsApiSettingsPutErrors];

export type PutSettingsApiSettingsPutResponses = {
    /**
     * Successful Response
     */
    200: SettingsOut;
};

export type PutSettingsApiSettingsPutResponse = PutSettingsApiSettingsPutResponses[keyof PutSettingsApiSettingsPutResponses];

export type OpenPerformerApiPerformersPerformerIdOpenPostData = {
    body?: never;
    path: {
        /**
         * Performer Id
         */
        performer_id: string;
    };
    query?: never;
    url: '/api/performers/{performer_id}/open';
};

export type OpenPerformerApiPerformersPerformerIdOpenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpenPerformerApiPerformersPerformerIdOpenPostError = OpenPerformerApiPerformersPerformerIdOpenPostErrors[keyof OpenPerformerApiPerformersPerformerIdOpenPostErrors];

export type OpenPerformerApiPerformersPerformerIdOpenPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type OpenPerformerApiPerformersPerformerIdOpenPostResponse = OpenPerformerApiPerformersPerformerIdOpenPostResponses[keyof OpenPerformerApiPerformersPerformerIdOpenPostResponses];

export type LocalSubdirsApiLocalSubdirsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/api/local/subdirs';
};

export type LocalSubdirsApiLocalSubdirsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LocalSubdirsApiLocalSubdirsGetError = LocalSubdirsApiLocalSubdirsGetErrors[keyof LocalSubdirsApiLocalSubdirsGetErrors];

export type LocalSubdirsApiLocalSubdirsGetResponses = {
    /**
     * Successful Response
     */
    200: SubdirsOut;
};

export type LocalSubdirsApiLocalSubdirsGetResponse = LocalSubdirsApiLocalSubdirsGetResponses[keyof LocalSubdirsApiLocalSubdirsGetResponses];

export type OpenPairApiOpenPairPostData = {
    body: OpenPairIn;
    path?: never;
    query?: never;
    url: '/api/open-pair';
};

export type OpenPairApiOpenPairPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpenPairApiOpenPairPostError = OpenPairApiOpenPairPostErrors[keyof OpenPairApiOpenPairPostErrors];

export type OpenPairApiOpenPairPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type OpenPairApiOpenPairPostResponse = OpenPairApiOpenPairPostResponses[keyof OpenPairApiOpenPairPostResponses];
